config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  namespace :admin do
    resources :users, only: [:index]
    resources :posts, except: [:show]
    resources :goals
  end
  match '/post', to: 'welcome#show', via: [:get]

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user

  validates :user_id, :name, :start_date, :due_date, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :taggings
  has_many :tags, through: :taggings
  belongs_to :user

  validates :user_id, :title, :body, presence: true

  after_create :persist_tags

  def self.tagged_with(name)
    Tag.find_by_name!(name).posts
  end

  def tag_string=(tags)
    @pending_tags = tags
  end

  def tag_string
    @pending_tags ||= self.tags.map {|t| t.name}.join(', ')
  end

  protected

  def persist_tags
    if @pending_tags
      split_tags = @pending_tags.split(',').map {|t| t.strip.downcase}
      split_tags.each do |tag|
        temp_tag = Tag.find_or_create_by(name: tag)
        temp_tag.taggings.find_or_create_by(post: self)
      end
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts, through: :taggings

  validates :name, presence: true
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post

  validates :post_id, :tag_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  def full_name
    first_name + ' ' + last_name
  end

  def is_admin?
    admin == true
  end
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/admin/goals_controller.rb
class Admin::GoalsController < ApplicationController
  before_filter :authorize!

  def index
    @goals = Goal.all
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(post_params)
    @goal.user = current_user

    if @goal.save
      redirect_to admin_goals_path
    else
      render 'new'
    end
  end

  private 

  def post_params
    params.require(:goal).permit(:name, :start_date, :due_date, :completed_date)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_filter :authorize!
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to admin_posts_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to admin_posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to admin_posts_path
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :tag_string)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authorize!
  def index
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authorize!
    if current_user.nil? or !current_user.is_admin?
      flash[:notice] = "You are not authorized to view this resource."
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if params[:tag]
      @posts = Tag.find_by(name: params[:tag]).posts
    else
      @posts = Post.all
    end
    @tags = Tag.all
    @goals = Goal.all
  end

  def show
    @post = Post.find(params[:format])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      sha = Digest::SHA1.hexdigest(code)
      Rails.cache.fetch ["code", language, sha].join('-') do
        Pygments.highlight(code, lexer: language)
      end
    end
  end

  def markdown(text)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/views/admin/goals/index.html.erb
<h1 id="all_goals">All Goals</h1>

<table>
  <tr>
    <th>User</th>
    <th>Name</th>
    <th>Start Date</th>
    <th>Due Date</th>
    <th>Completed? </th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <% @goals.each do |goal| %>
  <tr>
    <td> <%= goal.user_id %></td>
    <td> <%= goal.name %></td>
    <td> <%= goal.start_date.strftime("%B %d, %Y at %l%p") %></td>
    <td> <%= goal.due_date.strftime("%B %d, %Y at %l%p") %></td>
    <td> <%= goal.complete? %></td>
    <td> <%= link_to "Edit", edit_admin_goal_path(goal), class: "btn warning" %>  </td>
    <td> <%= link_to "Delete", admin_goal_path(goal), class: "btn danger", method: :delete, data: {confirm: "are you sure?"} %>  </td>
  <tr>
  <% end -%>
</table>

app/views/admin/goals/new.html.erb
<h1 id="new_goal">New Goal</h1>

<%= form_for [:admin, @goal], html: { class: 'ninja' } do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :start_date %>
  <%= f.datetime_select :start_date, :ampm => true, :minute_step => 15 %>

  <%= f.label :due_date %>
  <%= f.datetime_select :due_date, :ampm => true, :minute_step => 15 %>

  <%= f.submit 'Create Goal', class: "btn success" %>
<% end -%>

app/views/admin/posts/edit.html.erb
<h1 id="edit_post">Edit Post</h1>

<%= form_for [:admin, @post], html: {class: "ninja"} do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit 'Edit Post', class: "btn success" %>
<% end -%>

app/views/admin/posts/index.html.erb
<h1 id="all_posts">All Posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Created At</th>
    <th>Last Updated</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <% @posts.each do |post| %>
  <tr>
    <td> <%= post.title %></td>
    <td> <%= post.created_at.strftime("%B %d, %Y at %l%p") %></td>
    <td> <%= post.updated_at.strftime("%B %d, %Y at %l%p") %></td>
    <td> <%= link_to "Edit", edit_admin_post_path(post), class: "btn warning" %>  </td>
    <td> <%= link_to "Delete", admin_post_path(post), class: "btn danger", method: :delete, data: {confirm: "are you sure?"} %>  </td>
  <tr>
  <% end -%>
</table>

app/views/admin/posts/new.html.erb
<h1 id="new_post">New Post</h1>

<%= form_for [:admin, @post], html: {class: "ninja"} do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.label :tag_string %>
  <%= f.text_field :tag_string %>

  <%= f.submit 'Create Post', class: "btn success" %>
<% end -%>

app/views/admin/users/index.html.erb
<div class="row">
  <h1>Admin Namespace</h1>

  <table>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Admin?</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    <% @users.each do |user| %>
    <tr>
      <td> <%= user.first_name %></td>
      <td> <%= user.last_name %></td>
      <td> <%= user.email %></td>
      <td> <%= user.admin %></td>
      <td><a href="#" class="btn warning">Edit</a></td>
      <td><a href="#" class="btn danger">Delete</a></td>
    <tr>
    <% end -%>
  </table>
</div>

app/views/layouts/_nav.html.erb
<nav class="nav-inverse">
  <div class="brand">
    <h1>Spencer Dixon</h1>
  </div>
  <ul>
    <% if current_user %>
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Sign In', new_user_session_path, class: "call-to-action" %></li>
    <% end -%>

    <li><a href="/" class="active"> Home  </a></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spencer Dixon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/nav' %>

  <div class="container">
    <% if flash.any? %>
      <% if flash[:notice] %>
        <p class="alert success"><%= notice %></p>
      <% end %>

      <% if flash[:alert] %>
        <p class="alert danger"><%= alert %></p>
      <% end -%>
    <% end %>

    <% if current_user && current_user.is_admin? %>
      <%= link_to "All Users", admin_users_path, class: "btn info" %>
      <%= link_to "All Posts", admin_posts_path, class: "btn info" %>
      <%= link_to "All Goals", admin_goals_path, class: "btn info" %>
      <%= link_to "New Post", new_admin_post_path, class: "btn success" %>
      <%= link_to "New Goal", new_admin_goal_path, class: "btn success" %>
    <% end -%>

    <%= yield %>
  </div>

  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-51806130-2', 'auto');
    ga('send', 'pageview');
  </script>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome To Spencer Dixon's Personal Website</h1>
<p>This is an ever evolving project of mine. A place to experiment with new technologies and showcase some of my work.

My mission in life is to do everything in my power to live up to my full potential and help as many people as possible along the way. This website will act as a medium to share my story. To display my successes and my failures.

I was inspired to start this website by a good friend of mine Sam Shames. A dream come true for me would be for this website to someday inspire others.

If there is anyway I can add value to your life please feel free to contact me at: spencercdixon@gmail.com</p>
<h1>Tags</h1>
<p>
  <% @tags.each do |tag| %>
   <a href="?tag=<%= tag.name %>" class="btn info tagsize"> <%= tag.name %></a>
  <% end %>
</p>

<h1>Goals</h1>
<ol>
  <% @goals.each do |goal| %>
    <li> <%= goal.name %> .......... Will be done by: <%= goal.due_date.strftime("%B %d, %Y at %l%p")  %></li>
  <% end -%>
</ol>

<h1>Recent Posts</h1>
<ul class="posts">
<% @posts.each do |post| %>
  <li>
    <h1> <%= link_to post.title, post_path(post) %> </h1>
    <p> <%= post.created_at.strftime("%B %d, %Y at %l%p")  %></p>
    <%= markdown post.body %>
    <p> Written by: <%= post.user.full_name %> </p>
    <p>
      <% post.tags.each do |tag|  %>
        <a href="?tag=<%= tag.name %>" class="btn danger tagsize"> <%= tag.name %> </a>
      <% end -%>
    </p>
  </li>
<% end -%>
</ul>

app/views/welcome/show.html.erb
<h1> Post: <%= @post.title %></h1>
<p> <%= @post.created_at.strftime("%B %d, %Y at %l%p")  %></p>
  <%= markdown @post.body %>
<p> Written by: <%= @post.user.full_name %> </p>

<p>
  <% @post.tags.each do |tag|  %>
    <a href="/?tag=<%= tag.name %>" class="tags"> <%= tag.name %> </a>
  <% end -%>
</p>